2021-03-24 09:03:13,237 - ServerEntity.BattleAllocatorStub - INFO : [Stub.py:56]: Stub cannot connect to BattleAllocatorCenter, try again after 1 sec... (1)
2021-03-24 09:03:13,240 - ServiceFinder - INFO : [EtcdSupport.py:282]: add service node info--> BattleAllocatorCenter: ('192.168.82.177', 8888)
2021-03-24 09:03:13,241 - ServiceFinder - INFO : [EtcdSupport.py:282]: add service node info--> BattleAllocatorStub: ('192.168.82.177', 8889)
2021-03-24 09:03:13,242 - ServiceFinder - INFO : [EtcdSupport.py:282]: add service node info--> BattleAllocatorStub: ('192.168.82.177', 9000)
2021-03-24 09:03:13,243 - ServiceFinder - INFO : [EtcdSupport.py:236]: init service info from etcd success, will going to watch, at etcd index -> 13
2021-03-24 09:05:46,416 - ServiceNode - INFO : [EtcdSupport.py:476]: we have create ServiceRegister, wait 5 seconds
2021-03-24 09:05:46,417 - ServiceNode - INFO : [EtcdSupport.py:479]: we have create ServiceFinder
2021-03-24 09:05:46,423 - ServiceRegister - INFO : [EtcdSupport.py:148]: regist service : BattleAllocatorStub success, {"action":"set","node":{"key":"/services/BattleAllocatorStub/192.168.82.177|9000","value":"","expiration":"2021-03-24T01:08:46.4209046Z","ttl":180,"modifiedIndex":16,"createdIndex":16},"prevNode":{"key":"/services/BattleAllocatorStub/192.168.82.177|9000","value":"","expiration":"2021-03-24T01:06:08.225303Z","ttl":22,"modifiedIndex":13,"createdIndex":13}}

2021-03-24 09:05:50,427 - SingletonEntityManager - DEBUG : [SingletonEntityManager.py:118]: _register_relevant_centers_cb, status:good
2021-03-24 09:05:50,428 - ServerEntity.BattleAllocatorStub - INFO : [ServerEntity.py:21]: __init__ create entity BattleAllocatorStub with id 605a906efe754e33d4e7356b mem_id=1593465987136
2021-03-24 09:05:50,430 - server.EntityManager - INFO : [EntityManager.py:140]: addentity  entity id  605a906efe754e33d4e7356b 
2021-03-24 09:05:50,431 - SingletonEntityManager - INFO : [SingletonEntityManager.py:135]: BattleAllocatorStub connected to center
2021-03-24 09:05:50,433 - SingletonEntityManager - DEBUG : [SingletonEntityManager.py:137]: _register_stubs_cb, status:good
2021-03-24 09:05:51,422 - ServiceFinder - INFO : [EtcdSupport.py:282]: add service node info--> BattleAllocatorCenter: ('192.168.82.177', 8888)
2021-03-24 09:05:51,423 - ServiceFinder - INFO : [EtcdSupport.py:282]: add service node info--> BattleAllocatorStub: ('192.168.82.177', 8889)
2021-03-24 09:05:51,424 - ServiceFinder - INFO : [EtcdSupport.py:282]: add service node info--> BattleAllocatorStub: ('192.168.82.177', 9000)
2021-03-24 09:05:51,425 - ServiceFinder - INFO : [EtcdSupport.py:236]: init service info from etcd success, will going to watch, at etcd index -> 16
2021-03-24 09:07:00,430 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 16 -> 16
2021-03-24 09:08:04,432 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 16 -> 16
2021-03-24 09:09:12,439 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 16 -> 19
2021-03-24 09:10:18,430 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 19 -> 21
2021-03-24 09:11:18,431 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 21 -> 22
2021-03-24 09:12:25,434 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 22 -> 25
2021-03-24 09:13:30,437 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 25 -> 25
2021-03-24 09:14:36,428 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 25 -> 28
2021-03-24 09:15:39,431 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 28 -> 31
2021-03-24 09:16:47,439 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 31 -> 31
2021-03-24 09:17:55,427 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 31 -> 34
2021-03-24 09:18:57,434 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 34 -> 35
2021-03-24 09:20:03,437 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 35 -> 37
2021-03-24 09:21:11,441 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 37 -> 40
2021-03-24 09:22:12,451 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 40 -> 41
2021-03-24 09:23:13,453 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 41 -> 43
2021-03-24 09:24:19,447 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 43 -> 45
2021-03-24 09:25:23,451 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 45 -> 46
2021-03-24 09:26:30,459 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 46 -> 49
2021-03-24 09:27:33,463 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 49 -> 50
2021-03-24 09:27:58,802 - ServiceFinder - INFO : [EtcdSupport.py:382]: recv wath expire, info--> BattleAllocatorStub: ('192.168.82.177', 8889) - [51]
2021-03-24 09:29:05,806 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 51 -> 52
2021-03-24 09:30:09,810 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 52 -> 53
2021-03-24 09:31:09,814 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 53 -> 55
2021-03-24 09:32:11,806 - ServiceFinder - INFO : [EtcdSupport.py:422]: etcd watch timeout, rest watch index 55 -> 55
2021-03-24 09:32:52,967 - ServiceNode - INFO : [EtcdSupport.py:476]: we have create ServiceRegister, wait 5 seconds
2021-03-24 09:32:52,969 - ServiceNode - INFO : [EtcdSupport.py:479]: we have create ServiceFinder
2021-03-24 09:32:52,970 - ServiceRegister - DEBUG : [EtcdSupport.py:143]: _do_regist: now_url: http://192.168.82.177:2383/v2/keys/services/BattleAllocatorStub/192.168.82.177|9000
2021-03-24 09:32:52,975 - ServiceRegister - DEBUG : [EtcdSupport.py:148]: regist service : BattleAllocatorStub success, {"action":"set","node":{"key":"/services/BattleAllocatorStub/192.168.82.177|9000","value":"","expiration":"2021-03-24T01:35:52.9722599Z","ttl":180,"modifiedIndex":60,"createdIndex":60},"prevNode":{"key":"/services/BattleAllocatorStub/192.168.82.177|9000","value":"","expiration":"2021-03-24T01:34:28.817187Z","ttl":96,"modifiedIndex":56,"createdIndex":56}}

2021-03-24 09:32:56,964 - SingletonEntityManager - DEBUG : [SingletonEntityManager.py:118]: _register_relevant_centers_cb, status:good
2021-03-24 09:32:56,965 - ServerEntity.BattleAllocatorStub - INFO : [ServerEntity.py:21]: __init__ create entity BattleAllocatorStub with id 605a96c8fe754e1f881223b3 mem_id=1331921367104
2021-03-24 09:32:56,967 - server.EntityManager - INFO : [EntityManager.py:140]: addentity  entity id  605a96c8fe754e1f881223b3 
2021-03-24 09:32:56,968 - SingletonEntityManager - INFO : [SingletonEntityManager.py:135]: BattleAllocatorStub connected to center
2021-03-24 09:32:56,969 - SingletonEntityManager - DEBUG : [SingletonEntityManager.py:137]: _register_stubs_cb, status:good
2021-03-24 09:32:57,975 - ServerEntity.BattleAllocatorStub - INFO : [Stub.py:56]: Stub cannot connect to BattleAllocatorCenter, try again after 1 sec... (1)
2021-03-24 09:32:57,978 - ServiceFinder - INFO : [EtcdSupport.py:282]: add service node info--> BattleAllocatorCenter: ('192.168.82.177', 8888)
2021-03-24 09:32:57,980 - ServiceFinder - INFO : [EtcdSupport.py:282]: add service node info--> BattleAllocatorStub: ('192.168.82.177', 9000)
2021-03-24 09:32:57,981 - ServiceFinder - INFO : [EtcdSupport.py:282]: add service node info--> BattleAllocatorStub: ('192.168.82.177', 8889)
2021-03-24 09:32:57,982 - ServiceFinder - INFO : [EtcdSupport.py:236]: init service info from etcd success, will going to watch, at etcd index -> 60
