2021-03-08 15:26:24,374 - test_log - DEBUG : [LogManager.py:234]: debug message
2021-03-08 15:26:24,374 - test_log - INFO : [LogManager.py:235]: info message
2021-03-08 15:26:24,374 - test_log - WARNING : [LogManager.py:236]: warn message
2021-03-08 15:26:24,375 - test_log - ERROR : [LogManager.py:237]: error message
2021-03-08 15:26:24,375 - test_log - CRITICAL : [LogManager.py:238]: critical message
2021-03-08 15:26:24,375 - test_log - ERROR : on_traceback, type:<class 'ZeroDivisionError'>, value:division by zero, traceback:<class 'ZeroDivisionError'>
division by zero
  File "D:/Documents/github/realtime-server/pycharm2020.1.3/script/core/mobilelog/LogManager.py", line 241, in <module>
    locals={'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <_frozen_importlib_external.SourceFileLoader object at 0x00000199496D0970>, '__spec__': None, '__annotations__': {}, '__builtins__': <module 'builtins' (built-in)>, '__file__': 'D:/Documents/github/realtime-server/pycharm2020.1.3/script/core/mobilelog/LogManager.py', '__cached__': None, 'os': <module 'os' from 'C:\\Program Files\\Python38\\lib\\os.py'>, 'sys': <module 'sys' (built-in)>, 'logging': <module 'logging' from 'C:\\Program Files\\Python38\\lib\\logging\\__init__.py'>, 'ThreadPoolExecutor': <class 'concurrent.futures.thread.ThreadPoolExecutor'>, 'TimedRotatingFileHandler': <class 'logging.handlers.TimedRotatingFileHandler'>, 'inspect': <module 'inspect' from 'C:\\Program Files\\Python38\\lib\\inspect.py'>, '_tp_executor': <concurrent.futures.thread.ThreadPoolExecutor object at 0x00000199497AC730>, 'AsyncLogger': <class '__main__.AsyncLogger'>, 'LogManager': <class '__main__.LogManager'>, 'convert_python_tb_to_str': <function...
2021-03-08 15:33:34,967 - test_log - DEBUG : [LogManager.py:234]: debug message
2021-03-08 15:33:34,967 - test_log - INFO : [LogManager.py:235]: info message
2021-03-08 15:33:34,968 - test_log - WARNING : [LogManager.py:236]: warn message
2021-03-08 15:33:34,968 - test_log - ERROR : [LogManager.py:237]: error message
2021-03-08 15:33:34,968 - test_log - CRITICAL : [LogManager.py:238]: critical message
2021-03-08 15:33:34,968 - test_log - ERROR : on_traceback, type:<class 'ZeroDivisionError'>, value:division by zero, traceback:<class 'ZeroDivisionError'>
division by zero
  File "D:/Documents/github/realtime-server/pycharm2020.1.3/script/core/mobilelog/LogManager.py", line 241, in <module>
    locals={'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <_frozen_importlib_external.SourceFileLoader object at 0x0000025848870970>, '__spec__': None, '__annotations__': {}, '__builtins__': <module 'builtins' (built-in)>, '__file__': 'D:/Documents/github/realtime-server/pycharm2020.1.3/script/core/mobilelog/LogManager.py', '__cached__': None, 'os': <module 'os' from 'C:\\Program Files\\Python38\\lib\\os.py'>, 'sys': <module 'sys' (built-in)>, 'logging': <module 'logging' from 'C:\\Program Files\\Python38\\lib\\logging\\__init__.py'>, 'ThreadPoolExecutor': <class 'concurrent.futures.thread.ThreadPoolExecutor'>, 'TimedRotatingFileHandler': <class 'logging.handlers.TimedRotatingFileHandler'>, 'inspect': <module 'inspect' from 'C:\\Program Files\\Python38\\lib\\inspect.py'>, '_tp_executor': <concurrent.futures.thread.ThreadPoolExecutor object at 0x000002584A46C730>, 'AsyncLogger': <class '__main__.AsyncLogger'>, 'LogManager': <class '__main__.LogManager'>, 'convert_python_tb_to_str': <function...
